Search.appendIndex(
    [
                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\BasicCustomerEventPayloadListener",
            "name": "BasicCustomerEventPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-BasicCustomerEventPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\BasicCustomerEventPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020BasicCustomerEventPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-BasicCustomerEventPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\GenericEmailEventPayloadListener",
            "name": "GenericEmailEventPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-GenericEmailEventPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\GenericEmailEventPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020GenericEmailEventPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-GenericEmailEventPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\MergeCustomerPayloadListener",
            "name": "MergeCustomerPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-MergeCustomerPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\MergeCustomerPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020MergeCustomerPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-MergeCustomerPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload",
            "name": "BasicCustomerEventPayload",
            "summary": "Payload\u0020for\u0020deleting\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020deleting\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AgetCustomer\u0028\u0029",
            "name": "getCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_getCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AsetCustomer\u0028\u0029",
            "name": "setCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_setCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AgetSalesChannel\u0028\u0029",
            "name": "getSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_getSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AsetSalesChannel\u0028\u0029",
            "name": "setSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_setSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003A\u0024customer",
            "name": "customer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#property_customer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003A\u0024salesChannel",
            "name": "salesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#property_salesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload",
            "name": "GenericEmailEventPayload",
            "summary": "Payload\u0020for\u0020deleting\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020deleting\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_getEmail"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_setEmail"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_getSubject"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AsetSubject\u0028\u0029",
            "name": "setSubject",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_setSubject"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AgetText\u0028\u0029",
            "name": "getText",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_getText"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AsetText\u0028\u0029",
            "name": "setText",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_setText"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#property_email"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#property_subject"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A\u0024text",
            "name": "text",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#property_text"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload",
            "name": "MergeCustomerPayload",
            "summary": "Payload\u0020for\u0020merging\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020merging\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetNewCustomerId\u0028\u0029",
            "name": "getNewCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getNewCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetNewCustomerId\u0028\u0029",
            "name": "setNewCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setNewCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetNewExternalCustomerId\u0028\u0029",
            "name": "getNewExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getNewExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetNewExternalCustomerId\u0028\u0029",
            "name": "setNewExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setNewExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetNewSalesChannelId\u0028\u0029",
            "name": "getNewSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getNewSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetNewSalesChannelId\u0028\u0029",
            "name": "setNewSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setNewSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetOldCustomerId\u0028\u0029",
            "name": "getOldCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getOldCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetOldCustomerId\u0028\u0029",
            "name": "setOldCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setOldCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetOldExternalCustomerId\u0028\u0029",
            "name": "getOldExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getOldExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetOldExternalCustomerId\u0028\u0029",
            "name": "setOldExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setOldExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetOldSalesChannelId\u0028\u0029",
            "name": "getOldSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getOldSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetOldSalesChannelId\u0028\u0029",
            "name": "setOldSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setOldSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024newCustomerId",
            "name": "newCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_newCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024newExternalCustomerId",
            "name": "newExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_newExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024newSalesChannelId",
            "name": "newSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_newSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024oldCustomerId",
            "name": "oldCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_oldCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024oldExternalCustomerId",
            "name": "oldExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_oldExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024oldSalesChannelId",
            "name": "oldSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_oldSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService",
            "name": "MqService",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_customer_merge\u0028\u0029",
            "name": "send_customer_merge",
            "summary": "Send\u0020the\u0020customer.merge\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_customer_merge"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_customer_merge\u0028\u0029",
            "name": "subscribe_customer_merge",
            "summary": "Subscribe\u0020to\u0020the\u0020customer.merge\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_customer_merge"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_customer_delete\u0028\u0029",
            "name": "send_customer_delete",
            "summary": "Send\u0020the\u0020customer.delete\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_customer_delete"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_customer_delete\u0028\u0029",
            "name": "subscribe_customer_delete",
            "summary": "Subscribe\u0020to\u0020the\u0020customer.delete\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_customer_delete"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_customer_created\u0028\u0029",
            "name": "send_customer_created",
            "summary": "Send\u0020the\u0020customer.created\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_customer_created"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_customer_created\u0028\u0029",
            "name": "subscribe_customer_created",
            "summary": "Subscribe\u0020to\u0020the\u0020customer.created\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_customer_created"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_email_generic\u0028\u0029",
            "name": "send_email_generic",
            "summary": "Send\u0020the\u0020email.generic\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_email_generic"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_email_generic\u0028\u0029",
            "name": "subscribe_email_generic",
            "summary": "Subscribe\u0020to\u0020the\u0020email.generic\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_email_generic"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase",
            "name": "MqServiceBase",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020MqService\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AgetConnection\u0028\u0029",
            "name": "getConnection",
            "summary": "Get\u0020the\u0020AMQP\u0020connection\u0020instance.\u0020If\u0020it\u0020does\u0020not\u0020exist,\u0020it\u0020will\u0020be\u0020created.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_getConnection"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AcloseConnection\u0028\u0029",
            "name": "closeConnection",
            "summary": "Close\u0020the\u0020AMQP\u0020connection\u0020and\u0020channel,\nand\u0020therefore\u0020remove\u0020all\u0020subscriptions.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_closeConnection"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AgetChannel\u0028\u0029",
            "name": "getChannel",
            "summary": "Get\u0020the\u0020AMQP\u0020channel.\u0020If\u0020it\u0020does\u0020not\u0020exist,\u0020it\u0020will\u0020be\u0020created\u0020along\u0020with\u0020the\u0020queue.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_getChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "Publish\u0020a\u0020message\u0020to\u0020the\u0020service\u0027s\u0020queue,\u0020including\u0020the\u0020event\u0020name\u0020in\u0020the\u0020headers.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_publish"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003Asubscribe\u0028\u0029",
            "name": "subscribe",
            "summary": "Register\u0020a\u0020handler\u0020for\u0020a\u0020specific\u0020event\u0020type.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_subscribe"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AstartConsuming\u0028\u0029",
            "name": "startConsuming",
            "summary": "Start\u0020consuming\u0020messages\u0020and\u0020routing\u0020them\u0020to\u0020registered\u0020handlers.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_startConsuming"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AhandleMessage\u0028\u0029",
            "name": "handleMessage",
            "summary": "Handle\u0020an\u0020incoming\u0020message\u0020by\u0020routing\u0020it\u0020to\u0020the\u0020appropriate\u0020event\u0020handler.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_handleMessage"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Destructor\u0020to\u0020ensure\u0020connections\u0020are\u0020properly\u0020closed",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method___destruct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_connection"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024channel",
            "name": "channel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_channel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024eventHandlers",
            "name": "eventHandlers",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_eventHandlers"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_host"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024port",
            "name": "port",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_port"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_user"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_password"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024queueName",
            "name": "queueName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_queueName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024requeueUnhandled",
            "name": "requeueUnhandled",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_requeueUnhandled"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024vhost",
            "name": "vhost",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_vhost"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024exchange",
            "name": "exchange",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_exchange"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError",
            "name": "MqServiceError",
            "summary": "If\u0020a\u0020consumer\u0020returns\u0020an\u0020instance\u0020of\u0020this\u0020class,\nthe\u0020MqService\u0020will\u0020NOT\u0020acknowledge\u0020the\u0020message\u0020and\u0020requeue\u0020it.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020MqServiceError\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError\u003A\u003AgetRequeue\u0028\u0029",
            "name": "getRequeue",
            "summary": "Get\u0020whether\u0020to\u0020requeue\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html#method_getRequeue"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError\u003A\u003A\u0024requeue",
            "name": "requeue",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html#property_requeue"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners",
            "name": "Listeners",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-listeners.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-models.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events",
            "name": "Events",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP",
            "name": "OFCP",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp.html"
        },                {
            "fqsen": "\\Tecsafe",
            "name": "Tecsafe",
            "summary": "",
            "url": "namespaces/tecsafe.html"
        }            ]
);
