Search.appendIndex(
    [
                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap",
            "name": "EventMap",
            "summary": "The\u0020events\u0020constant\u0020must\u0020have\u0020the\u0020following\u0020structure\u003A",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003AgetTypeName\u0028\u0029",
            "name": "getTypeName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#method_getTypeName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003AgetEventName\u0028\u0029",
            "name": "getEventName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#method_getEventName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003ACUSTOMER_MERGE",
            "name": "CUSTOMER_MERGE",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_CUSTOMER_MERGE"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003ACUSTOMER_DELETE",
            "name": "CUSTOMER_DELETE",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_CUSTOMER_DELETE"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003ACUSTOMER_CREATED",
            "name": "CUSTOMER_CREATED",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_CUSTOMER_CREATED"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003AEMAIL_GENERIC",
            "name": "EMAIL_GENERIC",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_EMAIL_GENERIC"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003AEMAIL_BUTTON",
            "name": "EMAIL_BUTTON",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_EMAIL_BUTTON"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003ACOCKPIT_ADDREGISTRATION",
            "name": "COCKPIT_ADDREGISTRATION",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_COCKPIT_ADDREGISTRATION"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\EventMap\u003A\u003AEVENTS",
            "name": "EVENTS",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-EventMap.html#constant_EVENTS"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\ButtonEmailEventPayloadListener",
            "name": "ButtonEmailEventPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-ButtonEmailEventPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\ButtonEmailEventPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020ButtonEmailEventPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-ButtonEmailEventPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\CockpitAddRegistrationPayloadListener",
            "name": "CockpitAddRegistrationPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-CockpitAddRegistrationPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\CockpitAddRegistrationPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020CockpitAddRegistrationPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-CockpitAddRegistrationPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\CustomerCreatedEventPayloadListener",
            "name": "CustomerCreatedEventPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-CustomerCreatedEventPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\CustomerCreatedEventPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020CustomerCreatedEventPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-CustomerCreatedEventPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\CustomerDeleteEventPayloadListener",
            "name": "CustomerDeleteEventPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-CustomerDeleteEventPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\CustomerDeleteEventPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020CustomerDeleteEventPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-CustomerDeleteEventPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\GenericEmailEventPayloadListener",
            "name": "GenericEmailEventPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-GenericEmailEventPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\GenericEmailEventPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020GenericEmailEventPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-GenericEmailEventPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\MergeCustomerPayloadListener",
            "name": "MergeCustomerPayloadListener",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-MergeCustomerPayloadListener.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners\\MergeCustomerPayloadListener\u003A\u003Aon_event\u0028\u0029",
            "name": "on_event",
            "summary": "Handle\u0020the\u0020MergeCustomerPayload\u0020event.\u0020If\u0020returning\u0020false,\u0020the\u0020event\u0020will\u0020be\u0020requeued.",
            "url": "classes/Tecsafe-OFCP-Events-Listeners-MergeCustomerPayloadListener.html#method_on_event"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload",
            "name": "BasicCustomerEventPayload",
            "summary": "Payload\u0020for\u0020deleting\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020deleting\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AgetCustomer\u0028\u0029",
            "name": "getCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_getCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AsetCustomer\u0028\u0029",
            "name": "setCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_setCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AgetSalesChannel\u0028\u0029",
            "name": "getSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_getSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AsetSalesChannel\u0028\u0029",
            "name": "setSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_setSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003A\u0024customer",
            "name": "customer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#property_customer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BasicCustomerEventPayload\u003A\u003A\u0024salesChannel",
            "name": "salesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BasicCustomerEventPayload.html#property_salesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body",
            "name": "Body",
            "summary": "Email\u0020body\u0020attributs\u0020text\u003A\u0020Email\u0020text\u0020that\u0020will\u0020be\u0020added\u0020in\u0020the\u0020template\u0020\u007B\u007B\u0020text\u0020\u007D\u007D\u0020without\u0020html\u0020tags\u0020Links\u0020are\u0020parsed\u0020to\u0020anchor\u0020tags\u0020title\u003A\u0020Email\u0020title\u0020that\u0020will\u0020be\u0020added\u0020in\u0020the\u0020template\u0020\u007B\u007B\u0020title\u0020\u007D\u007D\u0020not\u0020the\u0020subject",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Email\u0020body\u0020attributs\u0020text\u003A\u0020Email\u0020text\u0020that\u0020will\u0020be\u0020added\u0020in\u0020the\u0020template\u0020\u007B\u007B\u0020text\u0020\u007D\u007D\u0020without\u0020html\u0020tags\u0020Links\u0020are\u0020parsed\u0020to\u0020anchor\u0020tags\u0020title\u003A\u0020Email\u0020title\u0020that\u0020will\u0020be\u0020added\u0020in\u0020the\u0020template\u0020\u007B\u007B\u0020title\u0020\u007D\u007D\u0020not\u0020the\u0020subject",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003AgetText\u0028\u0029",
            "name": "getText",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method_getText"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003AsetText\u0028\u0029",
            "name": "setText",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method_setText"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method_getTitle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method_setTitle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003A\u0024text",
            "name": "text",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#property_text"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Body\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Body.html#property_title"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData",
            "name": "BodyData",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020class\u0020represents\u0020the\u0020undefined\u0020model.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003AgetPrimatyButton\u0028\u0029",
            "name": "getPrimatyButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method_getPrimatyButton"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003AsetPrimatyButton\u0028\u0029",
            "name": "setPrimatyButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method_setPrimatyButton"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003AgetSecondaryButton\u0028\u0029",
            "name": "getSecondaryButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method_getSecondaryButton"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003AsetSecondaryButton\u0028\u0029",
            "name": "setSecondaryButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method_setSecondaryButton"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003A\u0024primatyButton",
            "name": "primatyButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#property_primatyButton"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyData\u003A\u003A\u0024secondaryButton",
            "name": "secondaryButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyData.html#property_secondaryButton"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton",
            "name": "BodyDataPrimatyButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020class\u0020represents\u0020the\u0020undefined\u0020model.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method_getTitle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method_setTitle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method_getUrl"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method_setUrl"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#property_title"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataPrimatyButton\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataPrimatyButton.html#property_url"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton",
            "name": "BodyDataSecondaryButton",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020class\u0020represents\u0020the\u0020undefined\u0020model.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method_getTitle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method_setTitle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method_getUrl"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method_setUrl"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#property_title"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\BodyDataSecondaryButton\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-BodyDataSecondaryButton.html#property_url"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload",
            "name": "ButtonEmailEventPayload",
            "summary": "Payload\u0020for\u0020sending\u0020emails\u0020with\u0020one\u0020to\u0020two\u0020buttons",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020sending\u0020emails\u0020with\u0020one\u0020to\u0020two\u0020buttons",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method_getBody"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003AsetBody\u0028\u0029",
            "name": "setBody",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method_setBody"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method_getHeader"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method_setHeader"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#property_body"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\ButtonEmailEventPayload\u003A\u003A\u0024header",
            "name": "header",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-ButtonEmailEventPayload.html#property_header"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload",
            "name": "CockpitAddRegistrationPayload",
            "summary": "Payload\u0020for\u0020add\u0020an\u0020user\u0020to\u0020the\u0020Cockpit",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020add\u0020an\u0020user\u0020to\u0020the\u0020Cockpit",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AgetExpirationDate\u0028\u0029",
            "name": "getExpirationDate",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_getExpirationDate"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AsetExpirationDate\u0028\u0029",
            "name": "setExpirationDate",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_setExpirationDate"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_getPassword"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_setPassword"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AgetRole\u0028\u0029",
            "name": "getRole",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_getRole"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AsetRole\u0028\u0029",
            "name": "setRole",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_setRole"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_getUser"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_setUser"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003A\u0024expirationDate",
            "name": "expirationDate",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#property_expirationDate"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#property_password"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003A\u0024role",
            "name": "role",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#property_role"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CockpitAddRegistrationPayload\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CockpitAddRegistrationPayload.html#property_user"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload",
            "name": "CustomerCreatedEventPayload",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020class\u0020represents\u0020the\u0020undefined\u0020model.",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003AgetCustomer\u0028\u0029",
            "name": "getCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method_getCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003AsetCustomer\u0028\u0029",
            "name": "setCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method_setCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003AgetSalesChannel\u0028\u0029",
            "name": "getSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method_getSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003AsetSalesChannel\u0028\u0029",
            "name": "setSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method_setSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003A\u0024customer",
            "name": "customer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#property_customer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerCreatedEventPayload\u003A\u003A\u0024salesChannel",
            "name": "salesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerCreatedEventPayload.html#property_salesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload",
            "name": "CustomerDeleteEventPayload",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020class\u0020represents\u0020the\u0020undefined\u0020model.",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003AgetCustomer\u0028\u0029",
            "name": "getCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method_getCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003AsetCustomer\u0028\u0029",
            "name": "setCustomer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method_setCustomer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003AgetSalesChannel\u0028\u0029",
            "name": "getSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method_getSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003AsetSalesChannel\u0028\u0029",
            "name": "setSalesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method_setSalesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003A\u0024customer",
            "name": "customer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#property_customer"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\CustomerDeleteEventPayload\u003A\u003A\u0024salesChannel",
            "name": "salesChannel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-CustomerDeleteEventPayload.html#property_salesChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload",
            "name": "GenericEmailEventPayload",
            "summary": "Payload\u0020for\u0020sending\u0020generic\u0020emails",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020sending\u0020generic\u0020emails",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_getBody"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AsetBody\u0028\u0029",
            "name": "setBody",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_setBody"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_getHeader"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_setHeader"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#property_body"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\GenericEmailEventPayload\u003A\u003A\u0024header",
            "name": "header",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-GenericEmailEventPayload.html#property_header"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header",
            "name": "Header",
            "summary": "Email\u0020header\u0020attreibutes\u0020to,\u0020from,\u0020cc,\u0020bcc,\u0020subject,\u0020are\u0020Required\u0020and\u0020are\u0020self\u0020explaining\u0020replyTo\u003A\u0020Optional\u0020the\u0020recipient\u0020of\u0020the\u0020reply\u0020returnPath\u0020\u003A\u0020Optional\u0020return\u0020path\u0020address\u0020of\u0020the\u0020email",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Email\u0020header\u0020attreibutes\u0020to,\u0020from,\u0020cc,\u0020bcc,\u0020subject,\u0020are\u0020Required\u0020and\u0020are\u0020self\u0020explaining\u0020replyTo\u003A\u0020Optional\u0020the\u0020recipient\u0020of\u0020the\u0020reply\u0020returnPath\u0020\u003A\u0020Optional\u0020return\u0020path\u0020address\u0020of\u0020the\u0020email",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetBcc\u0028\u0029",
            "name": "getBcc",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getBcc"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetBcc\u0028\u0029",
            "name": "setBcc",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setBcc"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetCc\u0028\u0029",
            "name": "getCc",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getCc"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetCc\u0028\u0029",
            "name": "setCc",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setCc"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetReservedFrom\u0028\u0029",
            "name": "getReservedFrom",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getReservedFrom"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetReservedFrom\u0028\u0029",
            "name": "setReservedFrom",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setReservedFrom"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetReplyTo\u0028\u0029",
            "name": "getReplyTo",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getReplyTo"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetReplyTo\u0028\u0029",
            "name": "setReplyTo",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setReplyTo"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetReturnPath\u0028\u0029",
            "name": "getReturnPath",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getReturnPath"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetReturnPath\u0028\u0029",
            "name": "setReturnPath",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setReturnPath"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getSubject"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetSubject\u0028\u0029",
            "name": "setSubject",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setSubject"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AgetTo\u0028\u0029",
            "name": "getTo",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_getTo"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AsetTo\u0028\u0029",
            "name": "setTo",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_setTo"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024reservedFrom",
            "name": "reservedFrom",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_reservedFrom"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_subject"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024to",
            "name": "to",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_to"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024bcc",
            "name": "bcc",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_bcc"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024cc",
            "name": "cc",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_cc"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024replyTo",
            "name": "replyTo",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_replyTo"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\Header\u003A\u003A\u0024returnPath",
            "name": "returnPath",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-Header.html#property_returnPath"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload",
            "name": "MergeCustomerPayload",
            "summary": "Payload\u0020for\u0020merging\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Payload\u0020for\u0020merging\u0020customers",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetNewCustomerId\u0028\u0029",
            "name": "getNewCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getNewCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetNewCustomerId\u0028\u0029",
            "name": "setNewCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setNewCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetNewExternalCustomerId\u0028\u0029",
            "name": "getNewExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getNewExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetNewExternalCustomerId\u0028\u0029",
            "name": "setNewExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setNewExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetNewSalesChannelId\u0028\u0029",
            "name": "getNewSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getNewSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetNewSalesChannelId\u0028\u0029",
            "name": "setNewSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setNewSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetOldCustomerId\u0028\u0029",
            "name": "getOldCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getOldCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetOldCustomerId\u0028\u0029",
            "name": "setOldCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setOldCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetOldExternalCustomerId\u0028\u0029",
            "name": "getOldExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getOldExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetOldExternalCustomerId\u0028\u0029",
            "name": "setOldExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setOldExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AgetOldSalesChannelId\u0028\u0029",
            "name": "getOldSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_getOldSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AsetOldSalesChannelId\u0028\u0029",
            "name": "setOldSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_setOldSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024newCustomerId",
            "name": "newCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_newCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024newExternalCustomerId",
            "name": "newExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_newExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024newSalesChannelId",
            "name": "newSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_newSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024oldCustomerId",
            "name": "oldCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_oldCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024oldExternalCustomerId",
            "name": "oldExternalCustomerId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_oldExternalCustomerId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\MergeCustomerPayload\u003A\u003A\u0024oldSalesChannelId",
            "name": "oldSalesChannelId",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-MergeCustomerPayload.html#property_oldSalesChannelId"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User",
            "name": "User",
            "summary": "user\u0020data\u0020attributes\u0020username,\u0020name,\u0020email,\u0020are\u0020Required\u0020and\u0020are\u0020self\u0020explaining\u0020type\u003A\u0020is\u0020Required\u0020and\u0020Define\u0020the\u0020type\u0020of\u0020the\u0020user\u0020\u005Binternal\u2503external\u2503service_account\u2503internal_service_account\u005D\u0020groups\u0020\u003A\u0020Optional,\u0020array\u0020of\u0020uuids\u0020of\u0020the\u0020groups\u0020the\u0020user\u0020is\u0020in",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "user\u0020data\u0020attributes\u0020username,\u0020name,\u0020email,\u0020are\u0020Required\u0020and\u0020are\u0020self\u0020explaining\u0020type\u003A\u0020is\u0020Required\u0020and\u0020Define\u0020the\u0020type\u0020of\u0020the\u0020user\u0020\u005Binternal\u2503external\u2503service_account\u2503internal_service_account\u005D\u0020groups\u0020\u003A\u0020Optional,\u0020array\u0020of\u0020uuids\u0020of\u0020the\u0020groups\u0020the\u0020user\u0020is\u0020in",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "Parse\u0020JSON\u0020data\u0020into\u0020an\u0020instance\u0020of\u0020this\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_getEmail"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_setEmail"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AgetGroups\u0028\u0029",
            "name": "getGroups",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_getGroups"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AsetGroups\u0028\u0029",
            "name": "setGroups",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_setGroups"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_getName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_setName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_getType"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AsetType\u0028\u0029",
            "name": "setType",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_setType"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_getUsername"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_setUsername"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#property_email"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#property_name"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#property_type"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#property_username"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models\\User\u003A\u003A\u0024groups",
            "name": "groups",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Models-User.html#property_groups"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService",
            "name": "MqService",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_customer_merge\u0028\u0029",
            "name": "send_customer_merge",
            "summary": "Send\u0020the\u0020customer.merge\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_customer_merge"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_customer_merge\u0028\u0029",
            "name": "subscribe_customer_merge",
            "summary": "Subscribe\u0020to\u0020the\u0020customer.merge\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_customer_merge"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_customer_delete\u0028\u0029",
            "name": "send_customer_delete",
            "summary": "Send\u0020the\u0020customer.delete\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_customer_delete"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_customer_delete\u0028\u0029",
            "name": "subscribe_customer_delete",
            "summary": "Subscribe\u0020to\u0020the\u0020customer.delete\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_customer_delete"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_customer_created\u0028\u0029",
            "name": "send_customer_created",
            "summary": "Send\u0020the\u0020customer.created\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_customer_created"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_customer_created\u0028\u0029",
            "name": "subscribe_customer_created",
            "summary": "Subscribe\u0020to\u0020the\u0020customer.created\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_customer_created"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_email_generic\u0028\u0029",
            "name": "send_email_generic",
            "summary": "Send\u0020the\u0020email.generic\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_email_generic"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_email_generic\u0028\u0029",
            "name": "subscribe_email_generic",
            "summary": "Subscribe\u0020to\u0020the\u0020email.generic\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_email_generic"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_email_button\u0028\u0029",
            "name": "send_email_button",
            "summary": "Send\u0020the\u0020email.button\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_email_button"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_email_button\u0028\u0029",
            "name": "subscribe_email_button",
            "summary": "Subscribe\u0020to\u0020the\u0020email.button\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_email_button"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asend_cockpit_addRegistration\u0028\u0029",
            "name": "send_cockpit_addRegistration",
            "summary": "Send\u0020the\u0020cockpit.addRegistration\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_send_cockpit_addRegistration"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqService\u003A\u003Asubscribe_cockpit_addRegistration\u0028\u0029",
            "name": "subscribe_cockpit_addRegistration",
            "summary": "Subscribe\u0020to\u0020the\u0020cockpit.addRegistration\u0020event.",
            "url": "classes/Tecsafe-OFCP-Events-MqService.html#method_subscribe_cockpit_addRegistration"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase",
            "name": "MqServiceBase",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020MqService\u0020class.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AopenConnection\u0028\u0029",
            "name": "openConnection",
            "summary": "Get\u0020the\u0020AMQP\u0020connection\u0020instance.\u0020If\u0020it\u0020does\u0020not\u0020exist,\u0020it\u0020will\u0020be\u0020created.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_openConnection"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AcloseConnection\u0028\u0029",
            "name": "closeConnection",
            "summary": "Close\u0020the\u0020AMQP\u0020connection\u0020and\u0020channel,\nand\u0020therefore\u0020remove\u0020all\u0020subscriptions.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_closeConnection"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AgetChannel\u0028\u0029",
            "name": "getChannel",
            "summary": "Get\u0020the\u0020AMQP\u0020channel.\u0020If\u0020it\u0020does\u0020not\u0020exist,\u0020it\u0020will\u0020be\u0020created\u0020along\u0020with\u0020the\u0020queue.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_getChannel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "Publish\u0020a\u0020message\u0020to\u0020the\u0020service\u0027s\u0020queue,\u0020including\u0020the\u0020event\u0020name\u0020in\u0020the\u0020headers.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_publish"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003Asubscribe\u0028\u0029",
            "name": "subscribe",
            "summary": "Register\u0020a\u0020handler\u0020for\u0020a\u0020specific\u0020event\u0020type.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_subscribe"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AstartConsuming\u0028\u0029",
            "name": "startConsuming",
            "summary": "Start\u0020consuming\u0020messages\u0020and\u0020routing\u0020them\u0020to\u0020registered\u0020handlers.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_startConsuming"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003AhandleMessage\u0028\u0029",
            "name": "handleMessage",
            "summary": "Handle\u0020an\u0020incoming\u0020message\u0020by\u0020routing\u0020it\u0020to\u0020the\u0020appropriate\u0020event\u0020handler.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method_handleMessage"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Destructor\u0020to\u0020ensure\u0020connections\u0020are\u0020properly\u0020closed",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#method___destruct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_connection"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024channel",
            "name": "channel",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_channel"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024eventHandlers",
            "name": "eventHandlers",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_eventHandlers"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024exchange",
            "name": "exchange",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_exchange"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_host"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024port",
            "name": "port",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_port"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_user"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_password"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024queueName",
            "name": "queueName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_queueName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024requeueUnhandled",
            "name": "requeueUnhandled",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_requeueUnhandled"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024vhost",
            "name": "vhost",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_vhost"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceBase\u003A\u003A\u0024exchangeName",
            "name": "exchangeName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceBase.html#property_exchangeName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError",
            "name": "MqServiceError",
            "summary": "If\u0020a\u0020consumer\u0020returns\u0020an\u0020instance\u0020of\u0020this\u0020class,\nthe\u0020MqService\u0020will\u0020NOT\u0020acknowledge\u0020the\u0020message\u0020and\u0020requeue\u0020it.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020MqServiceError\u0020class",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError\u003A\u003AgetRequeue\u0028\u0029",
            "name": "getRequeue",
            "summary": "Get\u0020whether\u0020to\u0020requeue\u0020the\u0020message\u0020or\u0020not.",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html#method_getRequeue"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\MqServiceError\u003A\u003A\u0024requeue",
            "name": "requeue",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-MqServiceError.html#property_requeue"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\OfcpEvent",
            "name": "OfcpEvent",
            "summary": "Basic\u0020interface\u0020for\u0020OFCP\u002DEvents.",
            "url": "classes/Tecsafe-OFCP-Events-OfcpEvent.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\OfcpEvent\u003A\u003Afrom_json\u0028\u0029",
            "name": "from_json",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-OfcpEvent.html#method_from_json"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Constants",
            "name": "Constants",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Constants.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Constants\u003A\u003AMESSENGER_OFCP_EVENTS_BUS_NAME",
            "name": "MESSENGER_OFCP_EVENTS_BUS_NAME",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Constants.html#constant_MESSENGER_OFCP_EVENTS_BUS_NAME"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Constants\u003A\u003AEVENT_NAME_HEADER",
            "name": "EVENT_NAME_HEADER",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Constants.html#constant_EVENT_NAME_HEADER"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Constants\u003A\u003ATRANSPORT_CONTENT_TYPE",
            "name": "TRANSPORT_CONTENT_TYPE",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Constants.html#constant_TRANSPORT_CONTENT_TYPE"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\EventNameMiddleware",
            "name": "EventNameMiddleware",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-EventNameMiddleware.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\EventNameMiddleware\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-EventNameMiddleware.html#method_handle"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\EventNameStamp",
            "name": "EventNameStamp",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-EventNameStamp.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\EventNameStamp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-EventNameStamp.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\EventNameStamp\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-EventNameStamp.html#method___toString"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\EventNameStamp\u003A\u003A\u0024eventName",
            "name": "eventName",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-EventNameStamp.html#property_eventName"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Serializer.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Serializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Serializer.html#method___construct"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Serializer\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Serializer.html#method_decode"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Serializer\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Serializer.html#method_encode"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Serializer\u003A\u003AhydrateMessage\u0028\u0029",
            "name": "hydrateMessage",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Serializer.html#method_hydrateMessage"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger\\Serializer\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-Messenger-Serializer.html#property_logger"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\TecsafeOfcpEventsBundle",
            "name": "TecsafeOfcpEventsBundle",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-TecsafeOfcpEventsBundle.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\TecsafeOfcpEventsBundle\u003A\u003AloadExtension\u0028\u0029",
            "name": "loadExtension",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-TecsafeOfcpEventsBundle.html#method_loadExtension"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\TecsafeOfcpEventsBundle\u003A\u003AprependExtension\u0028\u0029",
            "name": "prependExtension",
            "summary": "",
            "url": "classes/Tecsafe-OFCP-Events-Symfony-Bundle-TecsafeOfcpEventsBundle.html#method_prependExtension"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events",
            "name": "Events",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP",
            "name": "OFCP",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp.html"
        },                {
            "fqsen": "\\Tecsafe",
            "name": "Tecsafe",
            "summary": "",
            "url": "namespaces/tecsafe.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Listeners",
            "name": "Listeners",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-listeners.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-models.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle\\Messenger",
            "name": "Messenger",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-symfony-bundle-messenger.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony\\Bundle",
            "name": "Bundle",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-symfony-bundle.html"
        },                {
            "fqsen": "\\Tecsafe\\OFCP\\Events\\Symfony",
            "name": "Symfony",
            "summary": "",
            "url": "namespaces/tecsafe-ofcp-events-symfony.html"
        }            ]
);
