name: Publish to package registries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm i -g pnpm
      
      # Install dependencies
      - name: Install dependencies with pnpm
        run: pnpm install
      
      # Build and generate code
      - name: Build
        run: pnpm build
      - name: Check
        run: pnpm check
