name: Publish to package registries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Replace version in package.json to be semver compatible
        run: sed -i "s/IN-DEV/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" package.json
      
      # Install dependencies
      - name: Install dependencies with pnpm
        run: pnpm install && cd adapter/nestjs && pnpm install
      
      # Build and generate code
      - name: Build
        run: pnpm build
      - name: Check
        run: pnpm check
      
      # Documentation Sync
      - name: Move phpdoc into docs folder
        run: mv php/.phpdoc/build docs/php
      - name: Publish Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean-exclude: json-schema/
      
      # JSON Schema Sync
      - name: Prepare json-schema publication
        run: |
          mkdir -p json-schema
          cp dist/schema.json json-schema/$(echo $GITHUB_REF | sed 's/refs\/tags\///').json
          cp dist/schema.json json-schema/latest.json
      - name: Publish json-schema
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./json-schema
          destination_dir: json-schema
          publish_branch: gh-pages
          keep_files: true
      
      # Publish to registries
      - name: Publish package on NPM
        run: pnpm publish . --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
      
      # PHP Repo Sync
      - name: Load SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PHP_SECRET }}
      - name: Publish php source code to TECSAFE/event-sdk-php repository
        run: |
          git config --global user.email "noreply@tecsafe.de"
          git config --global user.name "CI Bot"
          git clone git@github.com:TECSAFE/event-sdk-php.git
          rm -rf event-sdk-php/*
          rm -rf php/.phpdoc
          mv php/* event-sdk-php/
          mv php/.* event-sdk-php/
          cp LICENSE event-sdk-php/
          echo "WARNING: This repository is automatically generated from the event-sdk repository." > event-sdk-php/README.md
          echo "Do not edit files in this repository directly." >> event-sdk-php/README.md
          echo "" >> event-sdk-php/README.md
          cat README.md >> event-sdk-php/README.md
          cd event-sdk-php
          git add .
          git commit -m "Update to version $(echo $GITHUB_REF | sed 's/refs\/tags\///')" && git push origin main || echo "No changes to commit"
          git tag $(echo $GITHUB_REF | sed 's/refs\/tags\///')
          git push origin --tags
